### ISSUE TITLE
exit_intent in chrome seems to fire on page load

### ISSUE THREAD

**Issue by Jetski5822** [shahzam/DialogTriggerJS#1]
When I load the page, it seems the exit_intent is fired straight away. Is this an expected intent?

My mouse in in the window of the browser window.

**Comment by shahzam** [comment]
@Jetski5822 that shouldn't be happening. Are you using Chrome on a PC or on a Mac?

Can you post the code snippet that is causing the exit_intent to fire right away?

**Comment by shoreline-chrism** [comment]
I'm seeing this issue too on Chrome/Windows.  Once I got the js to work on my wordpress site (I submitted other issue on that just now) I noticed that on chrome it fires instantly. I was testing on mobile and desktop using Chrome dev tools device emulator and it was happening in all cases using Chrome on Win.

Here's how I'm testing this function:

````
  window.dt = new DialogTrigger(alert("test"), { trigger: "exit_intent" });
````

I'm running that in my `$(document).ready()` function.

**Comment by shahzam** [comment]
@shoreline-chrism Thanks for the feedback! Can you try the following instead?

`window.dt = new DialogTrigger(function() { alert("test") }, { trigger: "exit_intent" });`

The callback expects a function with no parameters, so hopefully the above prevents the popup from activating instantly.

Let me know if that works.
