### ISSUE TITLE
JS won't work on Wordpress site or any other site using jQuery in no-conflict mode

### ISSUE THREAD

**Issue by shoreline-chrism** [shahzam/DialogTriggerJS#2]
This javascript is using the $ variable to reference jQuery but some websites run jQuery in no-conflict mode so you should change your `$` references to `jQuery` inside the function or wrap your whole function in a self-closing function:

````
(function($) {
  // Also maybe should make sure your function can be accessed outside your self-closing function
  window.DialogTrigger = function() {}
})(jQuery);
````

**Comment by shahzam** [comment]
@shoreline-chrism Thanks for pointing out this issue. I've updated the code so that it references `jQuery` instead of `$`. Let me know if that helps!
